config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :juicerecipes
root "juicerecipes#index"
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :juicerecipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :juicerecipe
end

app/models/juicerecipe.rb
class Juicerecipe < ActiveRecord::Base
	belongs_to :user
	
	has_many :ingredients
	has_many :directions

	accepts_nested_attributes_for :ingredients, 
								  reject_if: proc { |attributes| attributes['name'].blank? },
								  allow_destroy: true
	accepts_nested_attributes_for :directions, 
								  reject_if: proc { |attributes| attributes['step'].blank? },
								  allow_destroy: true

	validates :title, :description, :image, presence: true

	has_attached_file :image, :styles => { :medium => "400x400#" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :juicerecipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :null_session
end

app/controllers/juicerecipes_controller.rb
class JuicerecipesController < ApplicationController
	before_action :find_juicerecipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@juicerecipe = Juicerecipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@juicerecipe = current_user.juicerecipes.build
	end

	def create
		@juicerecipe = current_user.juicerecipes.build(juicerecipe_params)

		@juicerecipe.save1
 		@current_juicerecipe  = @pjuicerecipe
		@juicerecipes = Juicerecipe.all
	end

	def edit

		
	end

	def update
		if @juicerecipe.update(juicerecipe_params)
			redirect_to @juicerecipe
		else
			render 'edit'
		end
	end

	def destroy
		@juicerecipe.destroy
		redirect_to root_path, notice: "Successfully deleted juicerecipe"
	end

	private

	def juicerecipe_params
		params.require(:juicerecipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_juicerecipe
		@juicerecipe = Juicerecipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/juicerecipes_helper.rb
module JuicerecipesHelper
end

app/views/juicerecipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "form-button btn btn-default"

app/views/juicerecipes/_form.html.haml
= simple_form_for @juicerecipe, html: { multipart: true} do |f|
	- if @juicerecipe.errors.any?
		#errors
			%p
				= @juicerecipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @juicerecipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Steps', f, :directions, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"

app/views/juicerecipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/juicerecipes/create.js.haml
$('#juicerecipe-form').html("#{j (render @juicerecipe )}");
$('#juicerecipe-form').slideUp(350);

app/views/juicerecipes/edit.html.haml
%h1 Edit Juicerecipe

= render 'form'

app/views/juicerecipes/index.html.haml
- @juicerecipe.each_slice(3) do |juicerecipe|
	.row
		- juicerecipe.each do |juicerecipe|
			.col-md-4
				.juicerecipe
					.image_wrapper
						= link_to juicerecipe do
							= image_tag juicerecipe.image.url(:medium)
					%h2= link_to juicerecipe.title, juicerecipe
	
							
	

app/views/juicerecipes/new.html.haml
%h1 New Juicerecipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/juicerecipes/new.js.haml
$('#juice_box-form').html("#{j (render 'form')}");
$('#juice_box-form').slideDown(350);
if((obj = document.getElementById("submitbutton")) && obj != null){
window.scrollTo(0, obj.offsetTop);
}

app/views/juicerecipes/show.html.haml
.main_content
	#juicerecipe_top.row
		.col-md-4
			= image_tag @juicerecipe.image.url(:medium), class: "juice_image"
		.col-md-8
			#juicerecipe_info
				%h1= @juicerecipe.title
				%p.description= @juicerecipe.description
				%p
					Submitted by
					= @juicerecipe.user.email

	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @juicerecipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ul
					- @juicerecipe.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_juicerecipe_path, class: "btn btn-default"
				= link_to "Delete", juicerecipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Juice App
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Juice Box", root_path

			- if user_signed_in?
				%ul.new.navbar-nav.navbar-right
					%li= link_to "New Juices", new_juicerecipe_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.new.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path


		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert"
			= yield